michail-nikolaev/task-force-arma-3-radio

arma3/@task_force_radio/addons/task_force_radio/anarc164/anarc164.ext
arma3/@task_force_radio/addons/task_force_radio/anarc210/anarc210.ext
arma3/@task_force_radio/addons/task_force_radio/anprc148jem/anprc148jem.ext
arma3/@task_force_radio/addons/task_force_radio/anprc152/anprc152.ext
arma3/@task_force_radio/addons/task_force_radio/anprc154/anprc154.ext
arma3/@task_force_radio/addons/task_force_radio/anprc155/anprc155.ext
arma3/@task_force_radio/addons/task_force_radio/diver_radio/diver_radio.ext
arma3/@task_force_radio/addons/task_force_radio/fadak/fadak.ext
arma3/@task_force_radio/addons/task_force_radio/functions/fn_onDDDialogOpen.sqf
arma3/@task_force_radio/addons/task_force_radio/functions/fn_onLRDialogOpen.sqf
arma3/@task_force_radio/addons/task_force_radio/functions/fn_onSwDialogOpen.sqf
arma3/@task_force_radio/addons/task_force_radio/mr3000/mr3000.ext
arma3/@task_force_radio/addons/task_force_radio/mr6000l/mr6000l.ext
arma3/@task_force_radio/addons/task_force_radio/pnr1000a/pnr1000a.ext
arma3/@task_force_radio/addons/task_force_radio/rf7800str/rf7800str.ext
arma3/@task_force_radio/addons/task_force_radio/rt1523g/rt1523g.ext

It fires when the radio dialog is opened and when it is closed.
Event: OnRadioOpen
Parameters Passed:
0: OBJECT - unit (player)
1: STRING/ARRAY - radio
2: BOOL - LR radio
3: STRING - dialog name
4: BOOL - dialog open
https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/868

Added OnRadioOpen events to all radios.

---

ts/src/plugin.cpp

Changeable Plugin filenames

---

ts/src/plugin.cpp

Interaural level differences (one channel is louder than the other) are one of the two parts that make audio directional and clunk does not seem to apply it to the audio stream.
This is a very basic ILD implemenation which I used myself for a while now and it helps quite a bit with localizing persons that are talking to you.

ILD implementation

---

arma3/@task_force_radio/addons/task_force_radio/stringtable.xml
arma3/@task_force_radio/addons/task_force_radio_items/stringtable.xml

Just minor improvements and corrected grammar

Minor improvements for the German translation

---

README_EN.md
arma3/@task_force_radio/addons/task_force_radio/stringtable.xml

https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/977
Translations by Arma3Coop.pl

Polish translations

---

arma3/@task_force_radio/addons/task_force_radio/anarc210/anarc210.ext

Fix for #972

---

arma3/@task_force_radio/addons/task_force_radio_items/vehicles.hpp

see https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/993

Remove BWMod vehicles, fix updating base class issues (hopefully clean)

---

arma3/@task_force_radio/addons/task_force_radio/stringtable.xml

Line 1437 "Langstreckenfungerät" was missing a "k" for "Langstreckenfunkgerät".
Line 1872 replaced word "einzigartiges" with word "persönliches".
Lines 1990 - 2008 fixed some text, added line breaks.
Lines 2115 - 2117 added line breaks.
Lines 2197 - 2199 added line breaks.
Lines 2283 - 2287 updated informations, added line breaks.

Update German Stringtable.xml

---

arma3/@task_force_radio/addons/task_force_radio/stringtable.xml

Removed newline characters (~2000 characters), so source code formation doesn't effect ingame representation.
Picture:
https://img3.picload.org/image/iwiocrl/crlf.png
Edit: Only d089a24 is relevant. :)

Removed newline characters (stringtable.xml)

---

arma3/@task_force_radio/task_force_radio_pipe/task_force_radio_pipe.cpp
ts/include/dspfilters/Biquad.h
ts/include/dspfilters/Cascade.h
ts/src/plugin.cpp

Arma pipe extension:
Optimized and beautified RVExtension procedure.
TeamSpeak plugin:
Cleaned up some trash, fixed some bugs and undefined behaviour.

Optimized RVExt main procedure.

---

arma3/@task_force_radio/addons/task_force_radio/config.cpp

Fixes #1071

---

ts/include/dspfilters/Biquad.h
ts/include/dspfilters/Cascade.h

Fixed bug that i've made previously.

Fixed my bug

---

ts/src/plugin.cpp

Untested :disappointed: 
Related & explained #1056

Fix for #1056

---

arma3/@task_force_radio/task_force_radio_pipe/dllmain.cpp
arma3/@task_force_radio/task_force_radio_pipe/stdafx.h
arma3/@task_force_radio/task_force_radio_pipe/task_force_radio_pipe.cpp

Fixes #1109

---

addons/core/functions/fnc_isAbleToUseRadio.sqf
addons/core/functions/fnc_onAdditionalLRTangentPressed.sqf
addons/core/functions/fnc_onAdditionalSwTangentPressed.sqf
addons/core/functions/fnc_onDDTangentPressed.sqf
addons/core/functions/fnc_onLRTangentPressed.sqf
addons/core/functions/fnc_onSwTangentPressed.sqf
addons/core/functions/fnc_onSwTangentPressedHack.sqf

Fix for: #1134 
Also added headers to scripts that were changed as part of this fix.
Currently untested due to the build process being broken due to the various structural changes that have occured.

Fix TFAR_fnc_isAbleToUseRadio

---

addons/antennas/XEH_preInit.sqf

https://github.com/CBATeam/CBA_A3/pull/590

Update script because cba update

---

addons/core/stringtable.xml

sorry that previous pull
my bad..

korean trans for 1.0

---

addons/core/RscTitles.hpp

Fix to correct hints showing

---

addons/core/functions/fnc_setActiveSwRadio.sqf

If the player inventory is full, then when change the radio, the old one is deleted. So most likely easier.

Fix the loss of radio v2

---

addons/core/stringtable.xml

Pull request #1261 cleanup
originally by @NorXAengell

Stringtable french (#1261 fixed)

---

addons/antennas/CfgEventhandlers.hpp
addons/antennas/CfgVehicles.hpp
addons/antennas/XEH_PREP.sqf
addons/antennas/XEH_postInit.sqf
addons/antennas/XEH_preInit.sqf
addons/antennas/config.cpp
addons/antennas/functions/fnc_deleteRadioTower.sqf
addons/antennas/functions/fnc_initRadioTower.sqf
addons/antennas/functions/fnc_pluginAddRadioTower.sqf
addons/antennas/functions/fnc_pluginRemoveRadioTower.sqf
addons/antennas/script_component.hpp
addons/antennas/stringtable.xml

* Functionmacros
* header
* Splitting some files
* init-EH -> initPost-EH
* stringtable
* DEBUG-Stuff wrapped in macros
* empty file removed

Cleanup Antennas

---

addons/backpacks/anarc164/ui/anarc164.ext
addons/backpacks/anarc210/ui/anarc210.ext
addons/backpacks/anprc155/ui/anprc155.ext
addons/backpacks/bussole/ui/bussole.ext
addons/backpacks/mr3000/ui/mr3000.ext
addons/backpacks/mr6000l/ui/mr6000l.ext
addons/backpacks/rt1523g/ui/rt1523g.ext
addons/handhelds/anprc148jem/ui/anprc148jem.ext
addons/handhelds/anprc152/ui/anprc152.ext
addons/handhelds/anprc154/ui/anprc154.ext
addons/handhelds/fadak/ui/fadak.ext
addons/handhelds/pnr1000a/ui/pnr1000a.ext
addons/handhelds/rf7800/ui/rf7800str.ext

a typo i've recgnized after merging

typo in #1336

---

addons/core/CBA_Settings.sqf
addons/core/Cfg3DEN.hpp

- remove the 3DEN Channelsetting
- add the CBA-Setting for Channelname and PW
- needs next CBA

TS-Channelname changed into CBA_settings

---

addons/ai_hearing/XEH_PreInit.sqf
addons/core/functions/fnc_initCBASettings.sqf
addons/core/stringtable.xml

- Divides the settings into 2 categories
- Forces some settings to be only set by clients

settings categories

---

addons/core/XEH_preInit.sqf
addons/core/functions/fnc_initCBASettings.sqf
addons/core/functions/fnc_parseFrequenciesInput.sqf
addons/core/functions/plugin/fnc_sendPluginConfig.sqf

typo inside parseFreq fixed

---

addons/core/functions/fnc_initCBASettings.sqf

- forwardcompatibility for settings

settings - old variablenames replaced

---

addons/core/functions/fnc_processPlayerPositions.sqf

- cleanup TFAR_fnc_processPlayerPositions 
- do some small optimization inside TFAR_fnc_processPlayerPositions

TFAR_fnc_processPlayerPositions - cleanup&opti

---

addons/ai_hearing/XEH_PREP.sqf
addons/ai_hearing/XEH_PreInit.sqf
addons/ai_hearing/functions/fnc_OnRadioReceive.sqf
addons/ai_hearing/functions/fnc_onSettingChanged.sqf
addons/ai_hearing/functions/fnc_onSpeak.sqf
addons/ai_hearing/functions/fnc_revealInArea.sqf
addons/ai_hearing/stringtable.xml

- change the remoteExec into a CBA-Event
- some of the TODO
- cleanup
- reduced the remote calling by adding some additional checks
- new setting to enable the ai abillity to detect speakers on receive (has some limitations)

ai-hearing improvements

---

addons/core/functions/fnc_vehicleLr.sqf

- remove a useless comment
- default Value, required Datatype added

TFAR_fnc_VehicleLR

---

addons/core/functions/fnc_ClientInit.sqf
addons/core/functions/fnc_initCBASettings.sqf

- allows to change the PosUpdateMode onthefly

Allow change TFAR_PosUpdateMode onthefly

---

addons/core/functions/fnc_getWeaponConfigProperty.sqf

typo inside header

---

addons/core/functions/fnc_getLrSettings.sqf
addons/core/functions/fnc_getSwSettings.sqf

- remove the radiocode receiving from the unitside

change radio code receiving

---

addons/core/XEH_PREP.sqf
addons/core/functions/fnc_radioToRequestCount.sqf
addons/core/functions/server/fnc_missingModMessage.sqf
addons/core/functions/server/fnc_serverInit.sqf

- removed BIS_fnc_spawn
- sort PREP

missing mod message

---

addons/core/functions/fnc_lrRadiosList.sqf

add tfar_overrideactivelrradio

add TFAR_OverrideActiveLRRadio support

---

addons/ai_hearing/stringtable.xml
addons/core/stringtable.xml

- support to new entries
- fixed for few translations

Update Japanese translation

---

addons/backpacks/CfgVehicles.hpp
addons/backpacks/config.cpp
addons/backpacks/enoch/CfgVehicles.hpp

- Add backpack radio support for Contact DLC backpacks

Add support for radios in Contact DLC

---

addons/core/stringtable.xml

- Rename the above self-action menu item

Update stringtable.xml "IntercomChannel" to "Intercom Channel"

---

addons/core/stringtable.xml

Turkish Translation Upgraded by Grampalo (Core)

Turkish Translation

---

addons/core/functions/fnc_processPlayerPositions.sqf

- update player positions faster when player is in spectator

Faster position update in spectator

---

addons/backpacks/bussole/ui/bussole.hpp

- Fix script error when interacting with bussole radio UI
https://i.imgur.com/WTK5Krk.png

Fix bussole radio UI script error

---

addons/core/CfgEventHandlers.hpp
addons/core/XEH_PREP.sqf
addons/core/functions/events/fnc_onSplendidCamera.sqf
addons/core/functions/fnc_initCBASettings.sqf
addons/core/functions/fnc_lrRadiosList.sqf
addons/core/stringtable.xml

- Add ability to hear from Splendid Camera position, similar to Curator.
- Controlled by CBA Setting.

Hear from Splendid Camera

---

addons/core/functions/fnc_getSideRadio.sqf

Workaround for guer to independent in getSideRadio

---

CONTRIBUTORS.md
addons/ai_hearing/stringtable.xml
addons/backpacks/stringtable.xml
addons/core/stringtable.xml
addons/external_intercom/stringtable.xml
addons/handhelds/stringtable.xml
addons/static_radios/stringtable.xml

- added all missing Czech Translations
- resolved issue with Turkish duplicity(core.xml)

Czech translations

---

addons/ai_hearing/stringtable.xml
addons/backpacks/stringtable.xml
addons/core/stringtable.xml
addons/external_intercom/stringtable.xml
addons/handhelds/stringtable.xml
addons/static_radios/stringtable.xml

Add missed russian translations and fix existed.

Add missed russian translation

---

addons/ai_hearing/stringtable.xml
addons/core/stringtable.xml
addons/external_intercom/stringtable.xml
addons/static_radios/stringtable.xml

- Add Italian translation for external intercom and static radios
- Fix some Italian translation typos

Add and fix some Italian translations

---

addons/core/functions/events/keys/fnc_onAdditionalLRTangentReleased.sqf
addons/core/functions/events/keys/fnc_onAdditionalSwTangentReleased.sqf
addons/core/functions/events/keys/fnc_onLRTangentReleased.sqf
addons/core/functions/events/keys/fnc_onSwTangentReleased.sqf
addons/core/functions/fnc_ClientInit.sqf
addons/core/functions/plugin/fnc_releaseAllTangents.sqf

- Title.
- This addresses a bug where when you die (or go unconscious when ACE is loaded) while transmitting, it would require you, once you were respawned, to press the transmit button once before being able to actually transmit.

Finish transmissions upon all tangent release

---

CONTRIBUTORS.md
addons/core/XEH_PREP.sqf
addons/core/functions/events/handler/fnc_fireEventHandlers.sqf
addons/core/functions/intercom/fnc_canSetIntercomChannel.sqf
addons/core/functions/intercom/fnc_getIntercomChannel.sqf
addons/core/functions/intercom/fnc_setIntercomChannel.sqf
addons/core/functions/intercom/script_component.hpp
addons/core/intercomConfig/config.cpp

- Add dedicated functions for the condition and statement of intercom channels
- Add event for when an intercom channel is set

Intercom - Add functions and API event

---

addons/external_intercom/functions/fnc_connect.sqf

- fix condition of external intercom disconnecting

Fix disconnect condition
