michail-nikolaev/task-force-arma-3-radio

- debug/TaskForceRadioDebug.Altis/task_force_radio/bussole/bussole.ext
```
14:13:26 File C:\Users\Kavinsky\Documents\Arma 3\missions\TaskForceRadioDebug.Altis\task_force_radio\bussole\bussole.ext, line 186: '/bussole_radio_dialog/channel_04.tooltip': Missing ';' at the end of line
```
> Minor fix on bussole radio in debug mission

- arma3/@task_force_radio/addons/task_force_radio/functions/fn_generateLrSettings.sqf
- arma3/@task_force_radio/addons/task_force_radio/functions/fn_generateSwSettings.sqf
- debug/TaskForceRadioDebug.Altis/task_force_radio/functions/fn_generateLrSettings.sqf
- debug/TaskForceRadioDebug.Altis/task_force_radio/functions/fn_generateSwSettings.sqf
The parameters were always ignored, because it was getting compared to "BOOLEAN", which is not a valid typeName.
> Fixed BOOLEAN is not a valid typeName

- arma3/@task_force_radio/addons/task_force_radio/functions/fn_processPlayerPositions.sqf
Fix for: https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1078
Iam not sure if this is the best way to ensure that we have all players in the array.
It's untested.
> Fix: allUnits is not guaranteed to include allPlayers

- ts/src/plugin.cpp
I think that a user that installs the plugin either by copying the dlls or by creating a .ts3_plugin and executing it would expect it to be enabled on next TeamSpeak run.
Otherwise he would not install those plugin files at all.
Also this is one less step for people wanting to install the plugin, which also means one less potential problem for them.
> Load the plugin automatically, unless the user manually disabled it.

- arma3/@task_force_radio/addons/task_force_radio/functions/fn_ClientInit.sqf
- debug/TaskForceRadioDebug.Altis/task_force_radio/functions/fn_ClientInit.sqf
When merged this pull request will replace a call to `BIS_fnc_addStackedEventHandler` with the `addMissionEventHandler` command to make TFAR less vulnerable to the misuse/ abuse of the onEachFrame command.
> Replace Outdated EachFrame Code

- addons/core/ACEActions.hpp
- addons/core/XEH_PREP.sqf
- addons/core/functions/fnc_addRadiosToACE.sqf
- addons/core/functions/fnc_addStereoToACE.sqf
- addons/core/functions/fnc_getSwStereo.sqf
* the stereo settings added to the self interaction menu
* fix for the default value in TFAR_fnc_getSwStereo
* add the possibility to interact from inside vehicles, on chairs
* fixes #1328
> ACE3-Action: Stereo, inside Vehicles

- addons/core/functions/fnc_ClientInit.sqf
`TFAR_giveLongRangeRadioToGroupLeaders = tf_no_auto_long_range_radio;`
-> `TFAR_giveLongRangeRadioToGroupLeaders = ! tf_no_auto_long_range_radio;`
> old tf_no_auto_long_range_radio is not working right

- addons/core/functions/fnc_getRadioItems.sqf
fix function header
optimize the function
> optimizing getRadioItems

- addons/handhelds/radio_ids.hpp
and set `scopeArsenal = 2` ... so any _* radio is in the ACE Arsenal.
> Fix Unsung is overriding the ItemRadio class

- addons/core/functions/fnc_vehicleId.sqf
Why
=================
To allow for intercom use outside of a vehicle, but linked to an
intercom of a vehicle or set of vehicles.
Issue ID: N/A
- Allow units to use the intercom whenever the vehicleIDOverride variable is applied to them
- Intended for behind the scenes use, which is why no 3DEN attributes have been created to accompany this
> Added - Check for vehicleIDOverride existing on unit

- ts/src/SharedMemoryHandler.cpp
- Allow compiling Teamspeak plugin with latest MSVC 2019
> Fix MSVC compile issue with unicode character in stringstream

- addons/core/functions/fnc_hasRadio.sqf
- Change first condition to check for isNil due to the return of TFAR_fnc_backpackLr being nil if no backpack radio is worn.
- Also added isNotEqualTo to second condition.
> Fix hasRadio function

- addons/core/functions/fnc_initKeybinds.sqf
- addons/core/stringtable.xml
Add keybinds to cycle through radio channels.
Default keys:
CTRL + PAGEUP: Short Range radio channel increase
CTRL + PAGEDOWN: Short Range radio channel decrease
ALT + PAGEUP: Long Range radio channel increase
ALT + PAGEDOWN: Long Range radio channel decrease
Will require additional translations (only default and English are included).
> add keybinds to cycle through radio channels

- addons/core/CfgWeapons.hpp
- addons/core/config.cpp
- addons/core/functions/fnc_haveDDRadio.sqf
Changed the function haveDDRadio to use a config attribute instead of inheritance from `V_RebreatherB` to determine whether or not a player has a DD radio.
I tried to follow all naming and style rules i could see, if something should be changed feel free to point it out or change it yourself. Feel free to reject if this is not wanted this way.
- not change any noticable feature to a player
- allow developers to define vests as DD radios without having to inherit `V_RebreatherB`
- probably slightly increase performance of `fnc_haveDDRadio.sqf`
> fnc_haveDDRadio rewritten to use config attributes instead of inheritance

- addons/core/functions/plugin/fnc_sendPluginConfig.sqf
- ts/src/plugin.cpp
Fix hearing alive players (enemies/friendlies) when its disabled via settings.
Reason was wrong logic formula for isNotHearableInNonPureSpectator variable.
> Fix hearing alive players from spectator when its disabled

- addons/core/functions/fnc_forceSpectator.sqf
- addons/core/functions/fnc_processPlayerPositions.sqf
- addons/core/functions/plugin/fnc_isSpeaking.sqf
- addons/core/functions/plugin/fnc_releaseAllTangents.sqf
- addons/core/functions/plugin/fnc_sendFrequencyInfo.sqf
- addons/core/functions/plugin/fnc_sendPlayerKilled.sqf
This addresses the ideas/problems mentioned in #1463 and #1168 by allowing the name shown in TeamSpeak (and therefore used by the plugin) to be dynamically set using the variable `TFAR_unitName`.
- Modify all scripts using the players name to use one stored in a variable instead
- not change anything for players/developers if they don't use this feature
There are 2 considerations that need to be decided before merging this:
- should `TFAR_unitName` be set in some initialization script so defaults must not be used everywhere for performance reasons ? I don't know if this matters.
- can `TFAR_spectatorName` and `TFAR_unitName` be merged in one variable ? i don't see where it is ever set to something different than the players name but i don't know if …
> added ability to set custom teamspeak name

- addons/core/functions/plugin/fnc_sendPluginConfig.sqf
noAutoMoveSpectator is not sent to plugin. Players will no longer be moved into serious channel from spectator.
- sends the value of noAutomoveSpectator to the plugin
Solves #1560
> Add noAutoMoveSpectator into config that is sent to plugin

- addons/core/functions/fnc_initCBASettings.sqf
- addons/core/functions/plugin/fnc_sendPluginConfig.sqf
- addons/core/stringtable.xml
- ts/src/plugin.cpp
- ts/src/settings.hpp
- Adds option to mute other spectators
**Requires TS Addon update**
Is there a way to tell clients? Other than the warning of using unsupported config.
Should we also mute the player with this setting on and in spectator, so he doesn't *bother* other spectators unknowingly?
> Spectator mute

- addons/core/XEH_PREP.sqf
- addons/core/config.cpp
- addons/core/functions/stats/fnc_statCondition_encryptionCode.sqf
- addons/core/functions/stats/fnc_statCondition_isRadio.sqf
- addons/core/functions/stats/script_component.hpp
- Fix the encryption code stat showing on non-radio items
- Add generic "isRadio" condition function for other stats to potentially use
> Stats - Only show Encryption code stat for radios

- addons/core/functions/fnc_preparePositionCoordinates.sqf
- This forces all dead players to be muted, until they are in spectator or have respawned.
- This addresses players still be able to talk when they get killed, before being moved to spectator.
- I could add a setting, but I have a hard time thinking people wanting to not mute dead players until they are in spectator/have been respawned. If you think a setting is necessary, I can add one.
> Mute dead players automatically
